### ISSUE TITLE
u"Ω" errors in precompilation

### ISSUE THREAD

**Issue by YingboMa** [SymbolicML/DynamicQuantities.jl#105]
MWE: write the literal`u"Ω"` in a package that precompiles.

```julia
caused by: LoadError: Evaluation into the closed module `UnitsParse` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `UnitsParse` with `eval` during precompilation - don't do this.
Stacktrace:
  [1] eval
    @ Core ./boot.jl:385 [inlined]
  [2] eval
    @ DynamicQuantities.UnitsParse ~/.julia/packages/DynamicQuantities/5QflN/src/uparse.jl:1 [inlined]
  [3] uparse(s::String)
    @ DynamicQuantities.UnitsParse ~/.julia/packages/DynamicQuantities/5QflN/src/uparse.jl:37
  [4] var"@u_str"(__source__::LineNumberNode, __module__::Module, s::Any)
    @ DynamicQuantities.UnitsParse ~/.julia/packages/DynamicQuantities/5QflN/src/uparse.jl:57
...
```

**Comment by MilesCranmer** [comment]
As a quick fix you could do `import DynamicQuantities.Units: Ω` (or `.SymbolicUnits: Ω`) and work with the symbols directly.

It's weird that precompilation doesn't like it. Does anything in that module jump out to you? This is the file:

https://github.com/SymbolicML/DynamicQuantities.jl/blob/a31609fa9f732ded5a863b0f9a65211d78b7d889/src/uparse.jl#L1

**Comment by YingboMa** [comment]
It's probably due to the `eval` in https://github.com/SymbolicML/DynamicQuantities.jl/blob/a31609fa9f732ded5a863b0f9a65211d78b7d889/src/uparse.jl#L37

**Comment by MilesCranmer** [comment]
Oh I see. What other options are there for implementing this?

**Comment by YingboMa** [comment]
You can evaluate the expression yourself instead of `eval`.

**Comment by MilesCranmer** [comment]
Ah. Of course 🤦‍♂️

Thanks, will fix.

**Comment by MilesCranmer** [comment]
I guess we’ll need to do something a bit more complex like https://github.com/PainterQubits/Unitful.jl/blob/a09bdaac255d456e6315b77979a48956aca1d3a3/src/user.jl#L692 to get this working without `eval`.
