### ISSUE TITLE
Inconsistency between one(x::Quantity) and zero(x::Quantity)

### ISSUE THREAD

**Issue by FerreolS** [SymbolicML/DynamicQuantities.jl#138]
If `t` is a Quantity, the dimension is present in zero(t) but not in one(t) as in the following example:

```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.10.3 (2024-04-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using DynamicQuantities

julia> t=1u"m"
1.0 m

julia> one(t)
1.0 

julia> zero(t)
0.0 m

julia> oneunit(t)
1.0 m
```

**Comment by MilesCranmer** [comment]
This is the difference between one and oneunit. See https://docs.julialang.org/en/v1/base/numbers/#Base.oneunit

> If you want a quantity that is of the same type as x, or of type T, even if x is dimensionful, use [oneunit](https://docs.julialang.org/en/v1/base/numbers/#Base.oneunit) instead.

The way these are defined is that `one` is a multiplicative identity and `zero` is an additive identity. This is why `one` does not have units but `zero` does.
