### ISSUE TITLE
Suggestion: provide migration guide between breaking releases

### ISSUE THREAD

**Issue by isaacsas** [SymbolicML/DynamicQuantities.jl#147]
In trying to understand what ModelingToolkit-based packages need to go from v0.13 to v0.14 I’m struggling to find what needs to be modified. It would be helpful when making breaking releases to provide history files or such with explicit guidance on migrating to such releases, and information on what is breaking in a new major release. 

Thanks!

**Comment by MilesCranmer** [comment]
Good idea. For v0.13 to v0.14 the breaking change is very minor, it was just to add an additional method for `ustrip(::AbstractArray{<:AbstractQuantity})`. This is technically breaking which is why the minor version was incremented.

**Comment by MilesCranmer** [comment]
For v1.0.0 I describe that no changes are needed. Thanks for the issue, in the future I will also include this type of info in breaking releases!
