### ISSUE TITLE
Numerical value of 1 year (yr)

### ISSUE THREAD

**Issue by pmc4** [SymbolicML/DynamicQuantities.jl#149]
Right now 1 year is defined as 365.25 days, as seen in the [code](https://github.com/SymbolicML/DynamicQuantities.jl/blob/7e1b3f588a6e279ec332e387615b188ac3a843cf/src/units.jl#L191).

This definition is that of a julian year, defined with the symbol `a` as recommended by the International Astronomical Union (IAU). See [Table 5 here](https://www.iau.org/publications/proceedings_rules/units/).

The symbol `yr` is defined in the Particle Data Group (PDG) as a tropical year (from equinox to equinox) and it is equal to `1 yr = 365.242189 days`.  The PDG is a reliable source widely used in the physics community. See [Table 2.1 of the PDG](https://pdg.lbl.gov/2024/reviews/rpp2024-rev-astrophysical-constants.pdf) for this value.

I propose to redefine the current value of `yr` to be that of a julian year, `a`, and add the PDG value of a tropial year with the symbol `yr`.

**Comment by MilesCranmer** [comment]
There are many definitions of a year: https://en.wikipedia.org/wiki/Year so there's no "correct" and "incorrect" definition. It is true that the definition used in this package is 365.25 days. A user should always figure out what definition is being used in each context and adapt accordingly.

Note that the definition of a year used in DynamicQuantities.jl is the same as that in Unitful.jl (the most popular units package in Julia) as well as AstroPy (the most popular units package in Python).

Also, for stability of the package I am against changing the definition of any unit as it would break reproducibility, especially as we have just reached v1. What we should do instead is document precisely what definition is being used. Users can always give quantities in terms of SI units directly.

**Comment by pmc4** [comment]
You are right, "incorrect" was a bit strong and not appropiate. I'm sorry about that.

In such case, would it be possible to redefine a unit from the user side? So one can overwrite the package value of a unit without breaking anything.

**Comment by MilesCranmer** [comment]
No worries!

You can register new units: https://symbolicml.org/DynamicQuantities.jl/dev/units/#Custom-Units. So for example you could define an equinox-to-equinox year as `eyr`:

```julia
julia> using DynamicQuantities

julia> @register_unit eyr 365.242189u"day"

julia> 1u"eyr"
3.15569251296e7 s

julia> us"eyr"
1.0 eyr
```

You could also fork the repo and use a custom version locally

**Comment by pmc4** [comment]
That's a good solution. I guess that if I want to stick to my own value of `yr` I have to fork the repo and work locally. Thanks!
