### ISSUE TITLE
Add `iscompatible` to check if two quantities are compatible, e.g., `iscompatible(u"m", u"mm") == True`

### ISSUE THREAD

**Issue by bodokaiser** [SymbolicML/DynamicQuantities.jl#150]
It would be great to have such a check included. If someone is willing to give me a bit of guidance, I can prepare a PR.

**Comment by MilesCranmer** [comment]
Can already be done with `dimension(u"m") == dimension(u"mm")`. Is the `iscompatible` something from Unitful?

**Comment by bodokaiser** [comment]
I wasn't aware of `dimension(u"m") == dimension(u"mm")` and you are correct `Unitful` does the same, so I agree there is no need for `iscompatible` or the sort. Thank you!
