### ISSUE TITLE
Radian/Steradian

### ISSUE THREAD

**Issue by MilesCranmer** [SymbolicML/DynamicQuantities.jl#28]
Radians and steradians are dimensionless, but really should be treated like units. So far they have been excluded from the library (along with their derived units, like lumens and lux), but it could be useful to include them somehow. Maybe once #24 merges, there could be an alternate `RadQuantity`, `RadDimensions` objects for propagating these units, with promotion properties from regular `Quantity` objects so the units submodule can be used as normal.

**Comment by mikeingold** [comment]
Just to shamelessly advocate for my own interests, I would really love to be able to represent degrees, radians, and steradians in DynamicQuantities. As a EE, I use a lot of compound radiometric units and work in rotational systems.

**Comment by MilesCranmer** [comment]
Note the “Custom Dimensions” example here: https://symbolicml.org/DynamicQuantities.jl/dev/examples/#Custom-Dimensions

**Comment by MilesCranmer** [comment]
I’m not sure how to implement it more generally since radian is kind of a “fake” unit and formula written with it don’t necessarily cancel out correctly. Like for the formula `length = radius * angle`, you obviously wouldn’t have `radius` in terms of meters divided by a radian... basically wherever you pass an angle you would have to divide out a radian...

**Comment by MilesCranmer** [comment]
Added in #117
