### ISSUE TITLE
Feature suggestion: assignment of variables as unit during with `using DynamicQuantities: <list of units>`

### ISSUE THREAD

**Issue by briochemc** [SymbolicML/DynamicQuantities.jl#43]
With Unitful.jl, I can do

```julia
using Unitful: m, s
v = 3m/s
```

It would be great for feature-parity with Unitful if one could do

```julia
using DynamicQuantities: m, s
v = 3m/s
```

too, right?

**Comment by MilesCranmer** [comment]
You can currently do

```julia
using DynamicQuantities.Units: m, s
```

but maybe I could put the units in DynamicQuantities if that's better? Let me know and I can add it.

The only reason I didn't was to avoid polluting namespaces, and also to avoid name collisions between `DynamicQuantities.Constants` and `DynamicQuantities.Units`.

**Comment by briochemc** [comment]
Oh I did not know about this and I think that's good enough! 

Side (but related) question: How does one do the same thing for symbolic units?
